version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskdef.json"
        LoadBalancerInfo:
          ContainerName: "fe-chatbot"
          ContainerPort: 3000
        PlatformVersion: "1.4.0"
