version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "fe-chatbot"
    CONTAINER_NAME: throw
  exported-variables:
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION:-ap-northeast-2}
      - REPO_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO_URI
      - GIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Build Docker image"
      - docker build -t $IMAGE_REPO_NAME:latest -t $IMAGE_REPO_NAME:$GIT_SHA ./app
      - docker tag $IMAGE_REPO_NAME:$GIT_SHA $REPO_URI:$GIT_SHA
      - docker tag $IMAGE_REPO_NAME:latest $REPO_URI:latest
  post_build:
    commands:
      - echo "Push images"
      - docker push $REPO_URI:$GIT_SHA
      - docker push $REPO_URI:latest
      - echo "Prepare taskdef with new image"
      - sed -e "s|<IMAGE_URI>|$REPO_URI:$GIT_SHA|g" ci/taskdef.json > taskdef.json
artifacts:
  files:
    - taskdef.json
    - ci/appspec.yaml
