version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-2
    IMAGE_REPO_URI: 448091852876.dkr.ecr.ap-northeast-2.amazonaws.com/throw/fe-chatbot
    CONTAINER_NAME: fe-chatbot
    DOCKER_CONTEXT_PATH: . # Dockerfile이 하위 폴더면 경로 수정 (예: ./app)
phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $IMAGE_REPO_URI | cut -d'/' -f1)
      - GIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - echo "Commit tag: $GIT_SHA"
  build:
    commands:
      - echo "Build docker image"
      - docker build -t $IMAGE_REPO_URI:latest -t $IMAGE_REPO_URI:$GIT_SHA $DOCKER_CONTEXT_PATH
  post_build:
    commands:
      - echo "Push docker image to ECR"
      - docker push $IMAGE_REPO_URI:$GIT_SHA
      - docker push $IMAGE_REPO_URI:latest
      - echo "Prepare taskdef.json with new image"
      # ci/taskdef.json 템플릿에 <IMAGE_URI> 토큰이 있다고 가정
      - sed -e "s|<IMAGE_URI>|$IMAGE_REPO_URI:$GIT_SHA|g" ci/taskdef.json > taskdef.json
artifacts:
  files:
    - taskdef.json
    - ci/appspec.yaml
